config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true, except: [:index, :show, :new, :edit] do
      patch 'accept', on: :member
    end
  end
  resources :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :user_id, :question_id, :body, presence: true

  default_scope { order(accept: :desc, id: :asc) }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def accept!
    transaction do
      question.answers.update_all(accept: false)
      update!(accept: true)
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :user_id, :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :name, presence: true

  def author_of?(model)
    model.respond_to?(:user_id) && id == model.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:update, :destroy, :accept]
  before_action :set_question, only: [:create, :accept]

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user))
    if @answer.save
      flash_message :success, "Ответ успешно добавлен"
    else
      errors_to_flash(@answer)
    end
  end

  def update
    if current_user.author_of?(@answer)
      if @answer.update(answer_params)
        flash_message :success, "Ваш ответ успешно обновлен"
      else
        errors_to_flash(@answer)
      end
    else
      flash_message :error, "Only the author can edit answer"
    end
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      flash_message :success, 'Ответ успешно удален.'
    else
      flash_message :error, 'Запрешено удалять чужие ответы.'
    end
  end

  def accept
    if current_user.author_of?(@answer.question)
      @answer.accept!
    else
      flash_message :error, "Только автор вопроса может принимать ответ"
    end
  end

  private

  def set_answer
    @answer = Answer.find_by_id(params[:id])
  end

  def set_question
    @question = Question.find_by_id(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :admin, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    @question.attachments.build
    #@a = nil
  end

  def create
    @question = Question.new(question_params.merge(user: current_user))

    if @question.save
      redirect_to @question, notice: 'Вопрос успешно создан.'
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answer.attachments.build
  end

  def edit
  end

  def update
    if current_user.author_of?(@question)
      if @question.update(question_params)
        flash[:success] = "Вопрос успешно обновлен."
      else
        @question.errors.each_with_index do |x, i|
          flash["error#{i}".to_sym] = x[0].to_s.humanize+" "+x[1]
        end
      end
    else
      flash[:error] = "Only the author can edit question"
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      message = 'Вопрос успешно удален.'
    else
      message = 'Запрешено удалять чужие вопросы.'
    end
    redirect_to questions_path, notice: message
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def set_question
    @question = Question.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, messages|
      messages = messages.is_a?(Array) ? messages : [messages]
      messages.each do |message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
          concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
            concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
            concat content_tag(:span, 'Close', class: 'sr-only')
          end)
          concat message
        end)
      end
    end
    nil
  end

  def flash_message(type, text)
    flash[type] ||= []
    flash[type] << text
  end

  def errors_to_flash(model)
    if model && model.respond_to?(:errors) && model.errors.present?
      model.errors.full_messages.each { |m| flash_message :error, m }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div id='answer#{answer.id}'
    - if answer.accept
      div.accept
    = answer.body
    p
      | Attachments:
    ul
      - answer.attachments.each do |a|
        div id='attachment#{a.id}'
          li
            = link_to a.file.filename, a.file.url

    p
    - if current_user && current_user.author_of?(answer)
      = form_for answer, method: "patch", remote: true do |f|
        =f.label :body, 'Your answer'
        =f.text_area :body
        =f.fields_for :attachments do |attach|
          = render 'answers/attachment_fields', f: attach
          /= link_to_add_association 'add file', f, :attachments
        =f.submit 'Save'
      p
        = link_to "Edit", '', class: 'edit-answer-link', data: {answer_id: answer.id}
      p
        = link_to "Delete", answer, method: :delete, remote: true
    - if !answer.accept && current_user && current_user.author_of?(answer.question)
      p
        = link_to "Accept", accept_answer_path(answer),
                class: 'accept-answer-link', remote: true, method: :patch

app/views/answers/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
  .field
    - if f.object.new_record?
      = f.file_field :file
    - else
      = link_to f.object.file.filename, f.object.file.url
  = link_to_remove_association "remove file", f

app/views/answers/accept.js.erb
<%= render 'layouts/flash_messages' %>

<% if @answer.errors.empty? %>
  $("div#answers").html("<%= j render @answer.question.answers %>");
<% end %>

app/views/answers/create.js.erb
<%= render 'layouts/flash_messages' %>

<% if @answer.errors.empty? %>
  $(".answers").append("<%= j render @answer %>");
  $("#answer_body").val("");
<% end %>

app/views/answers/destroy.js.erb
<%= render 'layouts/flash_messages' %>

<% if @answer.errors.empty? %>
  $("div#answer<%= @answer.id %>").remove();
<% end %>

app/views/answers/update.js.erb
<%= render 'layouts/flash_messages' %>

<% if @answer.errors.empty? %>
  $("#answer<%= @answer.id %>").html("<%= j render @answer %>");
<% end %>

app/views/layouts/_flash_messages.js.erb
$("p.alert").html('');
$("p.notice").html('');
$('#flash_messages').html('<%= j flash_messages %>');

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "QnA"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"QnA
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              - unless devise_controller?
                - if user_signed_in?
                  li= link_to 'Log out', destroy_user_session_path, method: :delete
                - else
                  li= link_to 'Log in', new_user_session_path

    .container
      .row
        .col-lg-9
          div id="flash_messages"
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      p.notice
        = notice
      p.alert
        = alert

      footer
        p &copy; QnA 2016

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
    p
      = answer.body
      - if current_user && current_user.author_of?(answer)
        p
          = link_to "Delete answer #{answer.id}", answer, method: :delete

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
  .field
    - if f.object.new_record?
      = f.file_field :file
    - else
      = link_to f.object.file.filename, f.object.file.url
  = link_to_remove_association "remove file", f

app/views/questions/_question.html.slim
.question
  p
    | Title:
    = question.title

  p
    | Body:
    = question.body

  p
    | Attachments:
  ul
    - @question.attachments.each do |a|
      li= link_to a.file.filename, a.file.url

  p
  - if current_user && current_user.author_of?(question)
    = form_for question, remote: true do |f|
      p
        =f.label :title, 'Title'
        =f.text_field :title
      p
        =f.label :body, 'Your question'
        =f.text_area :body
      p
        = f.fields_for :attachments do |attach|
          = render 'attachment_fields', f: attach
      p
        =f.submit 'Save'

    div.row
      div.col-lg-1
        = link_to 'Edit', '', class: "edit-question-link btn btn-primary btn-sm", data: {question_id: @question.id}
      div.col-lg-2
        = link_to 'Delete question', @question, method: :delete, class: "btn btn-danger btn-sm"

app/views/questions/accept.js.erb
$("p.alert").html('');
$("p.notice").html('');

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>");
<% end %>

<% if @question.errors.empty? %>
  $("div#answers").html("<%= j render @question.answers %>");
<% end %>

app/views/questions/index.html.slim
- @questions.each do |question|
  =p link_to question.title, question

=p link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments
  p
  #attachments
    = f.fields_for :attachments do |attach|
      = render 'attachment_fields', f: attach
    .links
      = link_to_add_association 'add file', f, :attachments
  p
    = f.submit 'Create'

app/views/questions/show.html.slim
= render @question

.answers
  | Answers:
  div.row id='answers'
    = render @question.answers


= form_for [@question ,@answer], remote: true do |f|
  p
    = f.label :body
    = f.text_area :body
  p Attachments
  p
  #attachments
    = f.fields_for :attachments do |a|
      = render 'attachment_fields', f: a
      .links
        = link_to_add_association 'add file', f, :attachments
  p
    = f.submit 'Ask answer'

app/views/questions/update.js.erb
$("p.alert").html('');
$("p.notice").html('');

<% flash.each do |type, message| %>
  $("#flash_messages").html("<%= type.to_s.humanize %>: <%= message.html_safe %>");
<% end %>

<% if @question.errors.empty? %>
  $(".question").html("<%= j render @question %>");
  $('.edit-question-link').show();
<% end %>